### PR TITLE
Fix issue with active tabs not highlighted

### PR DESCRIPTION
**Pull request by mentrie**
@tsongas, looks good now

### CODE REVIEW

**Comment by tsongas** [comment]
Hmm merged this but still not working for me. The text turns white, I'm not sure why, but the active class doesn't get assigned so the background color doesn't change.

**Comment by tsongas** [comment]
I did see someone post the following in a forum:

Dan Brown [1:15 PM] 
activeClassName is gone :confused:

Dan Brown [1:29 PM] 
looks like there is a <NavLink> that isn’t in the docs, but supports activeClassName

**Comment by tsongas** [comment]
Never mind my other comments, this works for me although I would love to know how adding

null, null, { pure: false }

fixes the issue. I just added another commit where I figured out we could eliminate the eventKey and href attributes from the NavItem props, and just specify links like <LinkContainer to="/home">.

**Comment by tsongas** [comment]
I think this gives me some idea of what's happening https://github.com/reactjs/react-redux/blob/master/docs/troubleshooting.md.

**Comment by mentrie** [comment]
You've gotten the idea already. The other way to refactor it would be to make your `Header component` a stateless component. See [here](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).

**Pull request merged**
